config/routes.rb
Rails.application.routes.draw do
  resources :testes
  resources :herroos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/herroo.rb
class Herroo < ApplicationRecord
end

app/models/teste.rb
class Teste < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/herroos_controller.rb
class HerroosController < ApplicationController
  before_action :set_herroo, only: %i[ show edit update destroy ]

  # GET /herroos or /herroos.json
  def index
    @herroos = Herroo.all
  end

  # GET /herroos/1 or /herroos/1.json
  def show
  end

  # GET /herroos/new
  def new
    @herroo = Herroo.new
  end

  # GET /herroos/1/edit
  def edit
  end

  # POST /herroos or /herroos.json
  def create
    @herroo = Herroo.new(herroo_params)

    respond_to do |format|
      if @herroo.save
        format.html { redirect_to herroo_url(@herroo), notice: "Herroo was successfully created." }
        format.json { render :show, status: :created, location: @herroo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @herroo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /herroos/1 or /herroos/1.json
  def update
    respond_to do |format|
      if @herroo.update(herroo_params)
        format.html { redirect_to herroo_url(@herroo), notice: "Herroo was successfully updated." }
        format.json { render :show, status: :ok, location: @herroo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @herroo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /herroos/1 or /herroos/1.json
  def destroy
    @herroo.destroy

    respond_to do |format|
      format.html { redirect_to herroos_url, notice: "Herroo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_herroo
      @herroo = Herroo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def herroo_params
      params.require(:herroo).permit(:nome, :apelido)
    end
end

app/controllers/testes_controller.rb
class TestesController < ApplicationController
  before_action :set_testis, only: %i[ show edit update destroy ]

  # GET /testes or /testes.json
  def index
    @testes = Teste.all
  end

  # GET /testes/1 or /testes/1.json
  def show
  end

  # GET /testes/new
  def new
    @testis = Teste.new
  end

  # GET /testes/1/edit
  def edit
  end

  # POST /testes or /testes.json
  def create
    @testis = Teste.new(testis_params)

    respond_to do |format|
      if @testis.save
        format.html { redirect_to testis_url(@testis), notice: "Teste was successfully created." }
        format.json { render :show, status: :created, location: @testis }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @testis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testes/1 or /testes/1.json
  def update
    respond_to do |format|
      if @testis.update(testis_params)
        format.html { redirect_to testis_url(@testis), notice: "Teste was successfully updated." }
        format.json { render :show, status: :ok, location: @testis }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @testis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testes/1 or /testes/1.json
  def destroy
    @testis.destroy

    respond_to do |format|
      format.html { redirect_to testes_url, notice: "Teste was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testis
      @testis = Teste.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def testis_params
      params.fetch(:testis, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/herroos_helper.rb
module HerroosHelper
end

app/helpers/testes_helper.rb
module TestesHelper
end

app/views/herroos/_form.html.erb
<%= form_with(model: herroo) do |form| %>
  <% if herroo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(herroo.errors.count, "error") %> prohibited this herroo from being saved:</h2>

      <ul>
        <% herroo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :apelido %>
    <%= form.text_field :apelido %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/herroos/edit.html.erb
<h1>Editing Herroo</h1>

<%= render 'form', herroo: @herroo %>

<%= link_to 'Show', @herroo %> |
<%= link_to 'Back', herroos_path %>

app/views/herroos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Herroos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Apelido</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @herroos.each do |herroo| %>
      <tr>
        <td><%= herroo.nome %></td>
        <td><%= herroo.apelido %></td>
        <td><%= link_to 'Show', herroo %></td>
        <td><%= link_to 'Edit', edit_herroo_path(herroo) %></td>
        <td><%= link_to 'Destroy', herroo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Herroo', new_herroo_path %>

app/views/herroos/new.html.erb
<h1>New Herroo</h1>

<%= render 'form', herroo: @herroo %>

<%= link_to 'Back', herroos_path %>

app/views/herroos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @herroo.nome %>
</p>

<p>
  <strong>Apelido:</strong>
  <%= @herroo.apelido %>
</p>

<%= link_to 'Edit', edit_herroo_path(@herroo) %> |
<%= link_to 'Back', herroos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Heros</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/testes/_form.html.erb
<%= form_with(model: testis) do |form| %>
  <% if testis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(testis.errors.count, "error") %> prohibited this testis from being saved:</h2>

      <ul>
        <% testis.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/testes/edit.html.erb
<h1>Editing Testis</h1>

<%= render 'form', testis: @testis %>

<%= link_to 'Show', @testis %> |
<%= link_to 'Back', testes_path %>

app/views/testes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Testes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testes.each do |testis| %>
      <tr>
        <td><%= link_to 'Show', testis %></td>
        <td><%= link_to 'Edit', edit_testis_path(testis) %></td>
        <td><%= link_to 'Destroy', testis, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Testis', new_testis_path %>

app/views/testes/new.html.erb
<h1>New Testis</h1>

<%= render 'form', testis: @testis %>

<%= link_to 'Back', testes_path %>

app/views/testes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_testis_path(@testis) %> |
<%= link_to 'Back', testes_path %>